# Generated by Django 6.0.3 on 2026-03-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_newslatters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslatters',
            name='name',
            field=models.EmailField(max_length=250),
        ),
    ]
