# Generated by Django 6.0.3 on 2026-03-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_newslatters_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslatters',
            name='name',
        ),
        migrations.AddField(
            model_name='newslatters',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
