# Generated by Django 5.2 on 2026-02-27 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_counted_views_post_created_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_data',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated_data',
            new_name='updated_date',
        ),
    ]
