# Generated by Django 5.2 on 2026-03-05 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_created_data_post_created_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_date'], 'verbose_name': 'پوست', 'verbose_name_plural': 'پوست ها'},
        ),
    ]
