# Generated by Django 5.2 on 2026-03-05 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_date'], 'verbose_name': 'پوست', 'verbose_name_plural': 'پوست ها'},
        ),
    ]
