# Generated by Django 5.2 on 2026-03-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_category_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.URLField(blank=True),
        ),
    ]
