# Generated by Django 5.2 on 2026-03-10 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='address',
            new_name='address_github',
        ),
    ]
